"""Hand-curated keyword seeds for MITRE ATT&CK techniques.

The build script uses these to populate the `keywords` field for techniques
fetched fresh from MITRE CTI. Existing entries in mitre_techniques.json keep
their (already-tuned) keywords through the merge — these seeds only apply to
NEW T-IDs.

Coverage focus: post-compromise DFIR — Initial Access, Execution, Persistence,
Privilege Escalation, Defense Evasion, Credential Access, Discovery,
Lateral Movement, Collection, Command and Control, Exfiltration, Impact.

Each value is a list of 4-8 keywords / short phrases that, if found in a
finding description, signal the technique. Multi-word phrases use substring
match; single words use word-boundary regex.
"""

KEYWORD_SEEDS: dict[str, list[str]] = {
    # ── Initial Access ──────────────────────────────────────────────────────
    "T1078.001": ["default account", "default credentials", "guest account"],
    "T1078.003": ["local account", "local administrator", "local user"],
    "T1078.004": ["cloud account", "iam", "aws sts", "azure ad"],
    "T1189": ["drive-by", "compromise", "malicious site", "watering hole"],
    "T1195": ["supply chain", "dependency", "compromised package"],
    "T1195.001": ["software dependency", "package manager", "compromised library"],
    "T1199": ["trusted relationship", "third party", "msp", "contractor"],
    "T1200": ["hardware additions", "usb drop", "rogue device"],
    "T1566.001": ["spearphishing attachment", "phishing attachment", "malicious doc"],
    "T1566.002": ["spearphishing link", "phishing link", "credential harvest"],
    "T1566.003": ["spearphishing via service", "linkedin", "social"],

    # ── Execution ───────────────────────────────────────────────────────────
    "T1059.002": ["applescript", "osascript", "macos"],
    "T1059.003": ["cmd.exe", "command prompt", "batch", "windows command"],
    "T1059.004": ["bash", "/bin/sh", "shell script", "unix shell"],
    "T1059.005": ["vbscript", ".vbs", "wscript", "cscript"],
    "T1059.006": ["python", "python script", ".py"],
    "T1059.007": ["javascript", "node", "jscript", ".js"],
    "T1106": ["native api", "createprocess", "windows api"],
    "T1129": ["shared modules", "loadlibrary", "dll loaded"],
    "T1203": ["exploitation for client execution", "exploit", "memory corruption"],
    "T1204.001": ["malicious link", "user clicked", "open link"],
    "T1204.002": ["malicious file", "user opened", "double click"],
    "T1559.001": ["component object model", "com", "dcom"],
    "T1559.002": ["dynamic data exchange", "dde", "office"],

    # ── Persistence ─────────────────────────────────────────────────────────
    "T1037": ["boot logon", "initialization script", "autoexec"],
    "T1037.001": ["logon script", "windows logon", "kixstart"],
    "T1037.004": ["rc.local", "rc.common", "init script"],
    "T1098.001": ["additional cloud credentials", "access key", "iam key"],
    "T1098.002": ["email forwarding", "mailbox rule", "owa rule"],
    "T1136.001": ["create local account", "net user /add", "useradd"],
    "T1136.002": ["create domain account", "new-aduser", "domain user"],
    "T1176": ["browser extension", "chrome extension", "addon"],
    "T1197": ["bits jobs", "bitsadmin", "background intelligent transfer"],
    "T1543.001": ["launch agent", "launchd", "plist"],
    "T1543.004": ["launch daemon", "macos daemon"],
    "T1547.002": ["authentication package", "lsass dll", "lsa"],
    "T1547.004": ["winlogon helper", "userinit", "shell value"],
    "T1547.005": ["security support provider", "ssp"],
    "T1547.009": ["shortcut modification", ".lnk", "lnk file"],
    "T1547.014": ["active setup", "stubpath"],
    "T1554": ["compromise client software binary", "trojanized binary"],
    "T1556": ["modify authentication process", "skeleton key", "password filter"],

    # ── Privilege Escalation ────────────────────────────────────────────────
    "T1134": ["access token manipulation", "duplicate token", "impersonate"],
    "T1134.001": ["token impersonation", "duplicatetokenex", "make token"],
    "T1134.002": ["create process with token", "runas", "createprocessastoken"],
    "T1134.004": ["parent pid spoofing", "ppid spoof", "explorer.exe parent"],
    "T1484.001": ["group policy modification", "gpo", "gpedit"],
    "T1548.002": ["bypass user account control", "uac bypass", "fodhelper"],
    "T1548.003": ["sudo", "sudo caching", "sudoers"],
    "T1611": ["escape to host", "container escape", "docker"],

    # ── Defense Evasion ─────────────────────────────────────────────────────
    "T1027.002": ["software packing", "upx", "packed binary"],
    "T1027.003": ["steganography", "hidden in image", "steg"],
    "T1027.004": ["compile after delivery", "compiled on host"],
    "T1027.005": ["indicator removal from tools", "av evasion", "obfuscated"],
    "T1036": ["masquerading", "masquerade", "disguised process", "impersonated process name", "appears legitimate"],
    "T1036.001": ["invalid code signature", "forged signature", "spoofed signature", "invalid authenticode"],
    "T1036.002": ["right-to-left override", "rtlo", "rlo", "u+202e"],
    "T1036.003": ["rename system utilities", "renamed cmd", "renamed powershell"],
    "T1036.004": ["masquerade task or service", "fake service name"],
    "T1036.005": ["match legitimate name or location", "kworker", "kworkerd", "fake kernel worker", "fake system process name", "executable in /tmp", "svchost in temp"],
    "T1036.006": ["space after filename", "trailing space filename"],
    "T1036.007": ["double extension", ".pdf.exe", ".doc.exe"],
    "T1036.008": ["masquerade file type", "spoofed magic bytes", "mismatched magic bytes", "mismatched file signature", "file type mismatch", "extension content mismatch", "header extension mismatch"],
    "T1036.009": ["break process tree", "reparent process", "spoofed ppid", "parent pid spoofing", "ppid=1"],
    "T1070.002": ["clear linux logs", "rm /var/log", "wtmp"],
    "T1070.003": ["clear command history", ".bash_history", "history -c"],
    "T1070.004": ["file deletion", "del", "rm", "shred"],
    "T1070.005": ["network share connection removal", "net use /delete"],
    "T1070.008": ["clear mailbox data", "delete inbox", "mailbox rule"],
    "T1112": ["modify registry", "reg add", "regedit"],
    "T1140": ["deobfuscate", "decode files", "base64 decode", "xor decode"],
    "T1202": ["indirect command execution", "forfiles", "pcalua"],
    "T1218": ["signed binary proxy", "lolbin", "living off the land"],
    "T1218.001": ["compiled html file", ".chm", "hh.exe"],
    "T1218.005": ["mshta", "hta", ".hta"],
    "T1218.010": ["regsvr32", "scrobj", "sct file"],
    "T1218.011": ["rundll32", "rundll32.exe"],
    "T1480.001": ["environmental keying", "guard rails", "tied to host"],
    "T1497": ["sandbox detection", "vm detect", "anti-analysis"],
    "T1497.001": ["sandbox detection system check", "wmi query", "cpu check"],
    "T1542": ["pre-os boot", "bootkit", "mbr"],
    "T1553": ["subvert trust controls", "certificate", "signing"],
    "T1553.002": ["code signing", "signed driver", "valid certificate"],
    "T1564.001": ["hidden files", "ads", "alternate data stream"],
    "T1564.003": ["hidden window", "hidden console", "windowstyle hidden"],
    "T1574.001": ["dll search order hijacking", "search order"],
    "T1620": ["reflective code loading", "reflective dll", "in-memory"],

    # ── Credential Access ───────────────────────────────────────────────────
    "T1003.002": ["security account manager", "sam hive", "sam database"],
    "T1003.004": ["lsa secrets", "lsa.sav", "lsadump"],
    "T1003.005": ["cached domain credentials", "cached creds", "mscash"],
    "T1003.008": ["/etc/passwd", "/etc/shadow", "shadow file"],
    "T1040": ["network sniffing", "tcpdump", "wireshark"],
    "T1110.001": ["password guessing", "guess password"],
    "T1110.002": ["password cracking", "hashcat", "john the ripper"],
    "T1110.003": ["password spraying", "spray attack", "common password"],
    "T1110.004": ["credential stuffing", "leaked passwords"],
    "T1187": ["forced authentication", "smb relay", "ntlm relay"],
    "T1212": ["exploitation for credential access", "credential exploit"],
    "T1539": ["steal web session cookie", "cookie theft", "session token"],
    "T1552": ["unsecured credentials", "plaintext password", "config file"],
    "T1552.001": ["credentials in files", "password in script", "config.ini"],
    "T1552.002": ["credentials in registry", "reg cred"],
    "T1552.004": ["private keys", "id_rsa", ".ppk", ".pem"],
    "T1555": ["credentials from password stores", "password manager"],
    "T1555.003": ["browser credential dump", "chrome login data", "saved password"],
    "T1556.001": ["domain controller authentication", "skeleton key dc"],
    "T1556.003": ["pluggable authentication module", "pam"],
    "T1557": ["adversary in the middle", "mitm", "arp spoof"],
    "T1558": ["steal or forge kerberos", "kerberos"],
    "T1558.001": ["golden ticket", "krbtgt", "tgt"],
    "T1558.002": ["silver ticket", "tgs", "service ticket"],
    "T1558.003": ["kerberoasting", "spn", "service principal"],
    "T1606.001": ["web cookies", "saml forgery", "session forge"],

    # ── Discovery ───────────────────────────────────────────────────────────
    "T1007": ["system service discovery", "sc query", "tasklist"],
    "T1010": ["application window discovery", "enumerate windows"],
    "T1012": ["query registry", "reg query"],
    "T1016": ["system network configuration", "ipconfig", "ifconfig", "route"],
    "T1018": ["remote system discovery", "net view", "nslookup"],
    "T1033": ["system owner discovery", "whoami", "query user"],
    "T1046": ["network service scanning", "nmap", "port scan"],
    "T1049": ["system network connections", "netstat", "ss"],
    "T1057": ["process discovery", "ps", "tasklist", "get-process"],
    "T1069": ["permission groups discovery", "net group", "net localgroup"],
    "T1069.001": ["local groups", "net localgroup administrators"],
    "T1069.002": ["domain groups", "net group /domain"],
    "T1082": ["system information discovery", "systeminfo", "uname"],
    "T1083": ["file and directory discovery", "dir", "ls", "find /"],
    "T1087": ["account discovery", "net user", "net accounts"],
    "T1087.001": ["local account discovery", "net user", "/etc/passwd"],
    "T1087.002": ["domain account discovery", "net user /domain", "adusers"],
    "T1135": ["network share discovery", "net view", "smbclient"],
    "T1482": ["domain trust discovery", "nltest", "trust enumeration"],
    "T1518": ["software discovery", "wmic product"],
    "T1518.001": ["security software discovery", "tasklist sysmon", "av process"],

    # ── Lateral Movement ────────────────────────────────────────────────────
    "T1021.003": ["distributed component object model", "dcom lateral"],
    "T1021.004": ["ssh lateral", "ssh authorized keys", "remote ssh"],
    "T1080": ["taint shared content", "drop on share", "shared folder"],
    "T1210": ["exploitation of remote services", "remote exploit", "smb exploit"],
    "T1534": ["internal spearphishing", "internal phishing"],
    "T1550": ["use alternate authentication material", "pass the"],
    "T1550.002": ["pass the hash", "pth", "ntlm hash"],
    "T1550.003": ["pass the ticket", "ptt", "kerberos ticket"],

    # ── Collection ──────────────────────────────────────────────────────────
    "T1005": ["data from local system", "file collection", "documents"],
    "T1039": ["data from network shared drive", "shared folder collection"],
    "T1056.001": ["keylogger", "keystroke logging", "key capture"],
    "T1074": ["data staged", "staged data", "staging directory"],
    "T1074.001": ["local data staging", "temp staging", "%temp%"],
    "T1074.002": ["remote data staging", "staging server"],
    "T1113": ["screen capture", "screenshot", "printscreen"],
    "T1114": ["email collection", "mailbox harvest", "pst"],
    "T1114.001": ["local email collection", "outlook pst", "thunderbird"],
    "T1114.002": ["remote email collection", "exchange ews", "imap"],
    "T1115": ["clipboard data", "clipboard capture"],
    "T1119": ["automated collection", "scripted collection"],
    "T1123": ["audio capture", "microphone"],
    "T1125": ["video capture", "webcam"],
    "T1213": ["data from information repositories", "sharepoint", "confluence"],
    "T1530": ["data from cloud storage", "s3 bucket", "azure blob"],

    # ── Command and Control ─────────────────────────────────────────────────
    "T1008": ["fallback channels", "secondary c2"],
    "T1071.002": ["file transfer protocols", "ftp c2", "sftp"],
    "T1071.003": ["mail protocols", "smtp c2", "pop3 c2"],
    "T1092": ["communication through removable media", "usb c2"],
    "T1095": ["non-application layer protocol", "raw socket", "icmp tunnel"],
    "T1102": ["web service", "social media c2", "github c2"],
    "T1102.002": ["bidirectional communication", "two-way c2"],
    "T1104": ["multi-stage channels", "staged c2"],
    "T1105": ["ingress tool transfer", "downloaded tool", "tool drop"],
    "T1132": ["data encoding", "base64 c2", "encoded traffic"],
    "T1132.001": ["standard encoding", "base64", "base16"],
    "T1132.002": ["non-standard encoding", "custom encoding"],
    "T1205": ["traffic signaling", "port knock"],
    "T1219": ["remote access software", "teamviewer", "anydesk", "screenconnect"],
    "T1571": ["non-standard port", "uncommon port"],
    "T1572": ["protocol tunneling", "dns tunnel", "icmp tunnel"],
    "T1573": ["encrypted channel", "tls c2", "encrypted c2"],
    "T1573.001": ["symmetric cryptography", "aes c2", "rc4"],
    "T1573.002": ["asymmetric cryptography", "rsa c2", "public key"],

    # ── Exfiltration ────────────────────────────────────────────────────────
    "T1011": ["exfiltration over other network medium", "bluetooth exfil"],
    "T1020": ["automated exfiltration"],
    "T1029": ["scheduled transfer", "scheduled exfil"],
    "T1030": ["data transfer size limits", "chunked exfil"],
    "T1048.001": ["exfil over symmetric protocol"],
    "T1048.002": ["exfil over asymmetric protocol"],
    "T1048.003": ["exfiltration over unencrypted protocol", "ftp exfil"],
    "T1052": ["exfiltration over physical medium", "usb exfil"],
    "T1052.001": ["exfiltration over usb", "usb drive"],
    "T1567": ["exfiltration over web service", "dropbox", "anonfiles"],
    "T1567.001": ["exfiltration to code repository", "github exfil"],
    "T1567.002": ["exfiltration to cloud storage", "s3 exfil", "drive upload"],

    # ── Impact ──────────────────────────────────────────────────────────────
    "T1485": ["data destruction", "wiped", "shred"],
    "T1486": ["data encrypted for impact", "ransomware", "encrypted files"],
    "T1489": ["service stop", "stopped service", "net stop"],
    "T1490": ["inhibit system recovery", "vssadmin delete", "wbadmin delete"],
    "T1491": ["defacement", "website defaced"],
    "T1496": ["resource hijacking", "cryptominer", "xmrig"],
    "T1498": ["network denial of service", "ddos"],
    "T1499": ["endpoint denial of service", "resource exhaustion"],
    "T1529": ["system shutdown reboot", "shutdown /r", "force shutdown"],
    "T1531": ["account access removal", "disabled account", "locked account"],
    "T1561": ["disk wipe", "secure erase"],
    "T1561.001": ["disk content wipe", "dd if=/dev/zero"],
    "T1565": ["data manipulation", "altered data"],
    "T1565.001": ["stored data manipulation"],
    "T1565.002": ["transmitted data manipulation", "in-flight tampering"],
}
